#!/bin/bash
searches=(
    "There is no app configured at that hostname"
    "NoSuchBucket"
    "No Such Account"
    "You're Almost There"
    "a GitHub Pages site here"
    "this shop is currently unavailable"
    "There's nothing here"
    #"The site you were looking for couldn't be found"
    "The request could not be satisfied"
    "project not found"
    "Your CNAME settings"
    "InvalidBucketName"
    "PermanentRedirect"
    # from https://github.com/EdOverflow/can-i-take-over-xyz/
    "The specified bucket does not exist"
    "Repository not found"
#    "404 Not Found"
    "Bad Request: ERROR: The request could not be satisfied"
    "Fastly error: unknown domain:"
    "The thing you were looking for is no longer here, or never was"
    "There isn't a Github Pages site here."
    "We could not find what you're looking for."
    "No settings were found for this company:"
    "No such app"
    "Unrecognized domain"
    "Sorry, this shop is currently unavailable."
    "You are being redirected"
    "project not found"
    "The requested URL was not found on this server."
    "This UserVoice subdomain is currently available!"
    "Do you want to register"
)

for str in "${searches[@]}"; do
    grep -Hnri "$str" *
done
